### ISSUE TITLE
RTAI build broken in master

### ISSUE THREAD

**Issue by hdiethelm** [LinuxCNC/linuxcnc#3978]
In connection with https://github.com/LinuxCNC/linuxcnc/pull/3919 I wanted to test RTAI. However, build is broken:
 ```
  CC [M]  /home/hannes/linuxcnc-src/src/objects/hal/components/bin2gray.o
In file included from /home/hannes/linuxcnc-src/src/objects/hal/components/abs_s32.c:9:
/home/hannes/linuxcnc-src/src/../include/hal.h:995:36: warning: "__cplusplus" is not defined, evaluates to 0 [-Wundef]
  995 | #if __STDC_VERSION__ >= 202311L || __cplusplus
      |                                    ^~~~~~~~~~~
```
and many more:

[issue.txt](https://github.com/user-attachments/files/27196162/issue.txt)

Would it make sense to add a RTAI build to the CI?

**Comment by BsAtHome** [comment]
Interesting this was not caught in CI. Caused by #3936.

Fix is easy, should read:
```C
#if __STDC_VERSION__ >= 202311L || defined(__cplusplus)
```

**Comment by hdiethelm** [comment]
This also does not compile: https://github.com/LinuxCNC/linuxcnc/pull/3968
After reverting these on a local branch, I can build and test RTAI again.

**Comment by BsAtHome** [comment]
> This also does not compile: #3968

Can you please elaborate?

**Comment by hdiethelm** [comment]
Shure, sorry:
```
git checkout a3271af9d
./autogen.sh 
./configure --with-realtime=/usr/realtime-5.4.279-rtai-amd64
make
```

You can really easy test locally if it builds if you install rtai-modules-5.4.279, no need to have a kernel running.
```
/home/hannes/linuxcnc-src/src/objects/hal/components/latencybinstream.c: In function ‘export’:
/home/hannes/linuxcnc-src/src/objects/hal/components/latencybinstream.c:133:23: error: ‘INT64_MAX’ undeclared (first use in this function)
  133 |     inst->lat_min_p = INT64_MAX;
      |                       ^~~~~~~~~
/home/hannes/linuxcnc-src/src/objects/hal/components/latencybinstream.c:15:1: note: ‘INT64_MAX’ is defined in header ‘<stdint.h>’; this is probably fixable by adding ‘#include <stdint.h>’
  CC [M]  /home/hannes/linuxcnc-src/src/objects/hal/components/max31855.o
   14 | #include <rtapi_stdint.h>
  +++ |+#include <stdint.h>
   15 | #ifdef MODULE_INFO
/home/hannes/linuxcnc-src/src/objects/hal/components/latencybinstream.c:133:23: note: each undeclared identifier is reported only once for each function it appears in
  133 |     inst->lat_min_p = INT64_MAX;
      |                       ^~~~~~~~~
/home/hannes/linuxcnc-src/src/objects/hal/components/latencybinstream.c:134:23: error: ‘INT64_MIN’ undeclared (first use in this function); did you mean ‘INT_MIN’?
  134 |     inst->lat_max_p = INT64_MIN;
      |                       ^~~~~~~~~
      |                       INT_MIN
hal/components/latencybinstream.comp: In function ‘_’:
hal/components/latencybinstream.comp:129:13: error: ‘INT64_MAX’ undeclared (first use in this function)
hal/components/latencybinstream.comp:90:1: note: ‘INT64_MAX’ is defined in header ‘<stdint.h>’; this is probably fixable by adding ‘#include <stdint.h>’
hal/components/latencybinstream.comp:130:13: error: ‘INT64_MIN’ undeclared (first use in this function); did you mean ‘INT_MIN’?
make[2]: *** [scripts/Makefile.build:262: /home/hannes/linuxcnc-src/src/objects/hal/components/latencybinstream.o] Fehler 1
```

**Comment by BsAtHome** [comment]
Darn! Did include the correct header (rtapi_stdint.h) but used wrong names...

s/INT64_MAX/RTAPI_INT64_MAX/
s/INT64_MIN/RTAPI_INT64_MIN/

**Comment by BsAtHome** [comment]
We really need a CI build for RTAI with -Werror to ensure all these stupid mistakes get caught before they are merged.

**Comment by hdiethelm** [comment]
There is no CI with RTAI at all it looks like. I did not find the word rtai in `.github/workflows/ci.yml`

I'm used to gitlab CI's but github is a bit different.

**Comment by hdiethelm** [comment]
> Darn! Did include the correct header (rtapi_stdint.h) but used wrong names...
> 
> s/INT64_MAX/RTAPI_INT64_MAX/ s/INT64_MIN/RTAPI_INT64_MIN/

Happens to everyone, there are so many configurations, it is hard to manually test everything and the CI checks also only a few configurations.

Who maintains the CI? I mean I could try to add an RTAI target.

While going quickly through the CI logs, I also discovered that for each run, several GB of packages are downloaded and installed. This could be optimized by creating base docker images that already have the needed packages installed. It has to be tested if this really increases the speed but as it look now, in rip-and-test, installing takes 6 min / build&test 10 min.

I don't know how this can be done in github. In gitlab, we always do it this way.

**Comment by BsAtHome** [comment]
Should be fixed with #3981.

The CI is maintained just like many parts of LinuxCNC, like in the statement: <i>it buggered the hell out of me so much that I decided to fix it.</i>

I have no real experience with github  CI setup. Some one-liner changes, yes, but structural, no.

**Comment by hdiethelm** [comment]
> Should be fixed with [#3981](https://github.com/LinuxCNC/linuxcnc/pull/3981).
> 
> The CI is maintained just like many parts of LinuxCNC, like in the statement: it buggered the hell out of me so much that I decided to fix it.
> 
> I have no real experience with github CI setup. Some one-liner changes, yes, but structural, no.

Same for me for some of my PR's... ;-) Having a CI at all is already really nice.

I have some experience with way more complex CI's but I'm also not an expert. I think if I just change the CI file and create a PR, it will build my changes, I can test that to get an RTAPI CI, ok?

**Comment by BsAtHome** [comment]
> I have some experience with way more complex CI's but I'm also not an expert. I think if I just change the CI file and create a PR, it will build my changes, I can test that to get an RTAPI CI, ok?

I think you can just create a draft PR with adapted CI yaml file that will get executed on push. Having RTAI CI tested would be really nice.

**Comment by hdiethelm** [comment]
Ok, I will try that but might be not today. If you start it before, just tag me.
