### PR TITLE
hal: Fix implementation types and small adjustments

### PR DESCRIPTION
**Pull request by BsAtHome**
In this PR:
* Fix some types (still all compatible). The function signatures of the new functions were correct, but the implementations lagged.
* A long standing bug in hal_link would not properly copy the 64-bit value from the dummy to the signal, but would only set the lower 32-bit value. This has now been corrected.
* Final preparations are put in place for introducing the HAL query API.
* Update the comment in hal_init_data regarding the mutex.

This PR introduces hal_strerror() for textual representation of the negative error value from many of the HAL functions. The return value of some HAL functions will be adapted to become more fine-grained later. Currently, they mostly return -EINVAL, which often does not describe the actual error encountered. Changing the return value should not pose any problem because the code that actually checks return values looks for equality with zero or less than zero. Returning a more differentiating (negative) value does not functionally alter that code but allows better messages to be generated moving forward.

### CODE REVIEW

File: src/hal/hal_lib.c [hunk 1]
```diff
@@ -462,6 +462,25 @@ int hal_exit(int comp_id)
     return 0;
 }
 
+int hal_is_init(void)
```
Comment (grandixximo) [inline src/hal/hal_lib.c:465]: Doesn't this need the matching declaration of public prototype
`extern int hal_is_init(void);`
in `hal.h` ?

File: src/hal/hal_lib.c [hunk 2]
```diff
@@ -662,9 +708,12 @@ int hal_set_lock(unsigned char lock_type) {
...
     if (hal_data == NULL) {
-	rtapi_print_msg(RTAPI_MSG_ERR,
-	    "HAL: ERROR: get_lock called before init\n");
-	return -EINVAL;
+        rtapi_print_msg(RTAPI_MSG_ERR, "HAL: ERROR: get_lock called before init\n");
+	// There is no point in returning a negative error value. The return
+	// type wont allow it. We just pretend that everything is locked tight
+	// and nothing can change, which would adequately describe the
+	// unavailability of shared memory.
+        return HAL_LOCK_ALL;
```
Comment (grandixximo) [inline src/hal/hal_lib.c:716]: Are we OK with propagating the _(IMO horrible)_ spaces-tab-spaces indent style now?

File: src/hal/hal_lib.c [hunk 3]
```diff
@@ -620,6 +639,33 @@ int hal_unready(int comp_id) {
...
+    case -ERANGE:  return "value out of range";
+    case -ENOMEM:  return "out of memory";
+    case -EISCONN: return "queue already allocated";
+    case -EEXIST:  return "name exists";  // also when pin/param/sig matched with different type
+    case -EFAULT:  return "shared memory not mapped";
+    case -EMFILE:  return "too many modules";
+    case -EPROTO:  return "hal data version mismatch";
+    case -EPERM:   return "hal is locked";
+    case -ENOEXEC: return "missing constructor";
+    default:       return "unknown error";
```
Comment (grandixximo) [inline src/hal/hal_lib.c:665]: Would 
`default: return strerror(-err)`
be better here?

**Comment by grandixximo** [comment]
If merge this first my #4251 will fail to build, can you provide an explicit marker like

`#define HAL_HAS_QUERY_API 1`

And I re-gate #4251 on that?

File: src/hal/hal_lib.c (hunk 1 above)
Comment (BsAtHome) [reply src/hal/hal_lib.c:465]: Yes, but that is postponed to the rest of the query API. It got copied in and later realized that the prototype was missing. Should be no problem because it is not yet used.

File: src/hal/hal_lib.c (hunk 3 above)
Comment (BsAtHome) [reply src/hal/hal_lib.c:665]: I did think about that. The problem is that these error messages are not "standard" errno messages. They are geared specifically towards HAL.
Another problem is that strerror() has a `char *` return and uses a static buffer internally. That I'd like to avoid very much.

Comment (grandixximo) [reply src/hal/hal_lib.c:665]: Fair

File: src/hal/hal_lib.c (hunk 2 above)
Comment (BsAtHome) [reply src/hal/hal_lib.c:716]: Missed that one. Happens when I modify existing code and don't double check. Good you are looking.

**Comment by BsAtHome** [comment]
> If merge this first my #4251 will fail to build, can you provide an explicit marker like

Why and where does that fail?

File: src/hal/hal.h [hunk 4]
```diff
@@ -556,6 +561,7 @@ int hal_param_new_ui32(int compid, hal_pdir_t dir, hal_uint_t *ref, rtapi_u32  d
 int hal_param_new_sint(int compid, hal_pdir_t dir, hal_sint_t *ref, rtapi_sint def, const char *fmt, ...) __HAL_PFMT(5,6);
 int hal_param_new_uint(int compid, hal_pdir_t dir, hal_uint_t *ref, rtapi_uint def, const char *fmt, ...) __HAL_PFMT(5,6);
 int hal_param_new_real(int compid, hal_pdir_t dir, hal_real_t *ref, rtapi_real def, const char *fmt, ...) __HAL_PFMT(5,6);
+int hal_param_new_fake(int compid, hal_refs_u *refs);
```
Comment (grandixximo) [inline src/hal/hal.h:564]: Would like to see a comment for API consumer like
`// opaque-by-design, callers must not assume the size.`
or a guarantee the size irrelevant by contract
```
/* hal_param_new_fake() allocates backing storage for one HAL value of any
 * type without registering a named parameter. The returned storage is
 * opaque; access it only through the typed ref members. */
```

Comment (BsAtHome) [reply src/hal/hal.h:564]: There is a man-page coming for this.

**Comment by BsAtHome** [comment]
BTW, the next PR will provide the HAL query API. That should make most changes to these parts complete.

**Comment by grandixximo** [comment]
> > If merge this first my #4251 will fail to build, can you provide an explicit marker like
> 
> Why and where does that fail?

I will double check the claim in a few hours once I'm on a linux machine

arm sid is broken, are we closing an eye on that?

**Comment by BsAtHome** [comment]
And now CI/Sid is acting up again. Sid has been very unstable lately.

**Comment by BsAtHome** [comment]
> I will double check the claim in a few hours once I'm on a linux machine

Haven't used anything else for 28 years :-)

> arm sid is broken, are we closing an eye on that?

Hm, our messages crossed. Email notify has not yet arrived. Sometimes...

**Comment by grandixximo** [comment]
I don't sid being obviously broken should stall us...

**Comment by BsAtHome** [comment]
> I don't sid being obviously broken should stall us...

I don't think it is a problem either.

**Comment by grandixximo** [comment]
> > If merge this first my #4251 will fail to build, can you provide an explicit marker like
> 
> Why and where does that fail?

It fails because of how I detect the query API in #4251. My by-name code (`hal_getref_p` etc.) only exists once the query API PR lands, so I gated it on

    #if defined(COMPONENT_TYPE_REALTIME)

using the enum as a proxy for "query API is present", because your query PR was the one that introduced that macro in the public header.

This PR moves COMPONENT_TYPE_* into public hal.h on its own, ahead of the query API. From that point the macro is defined but `hal_getref_p` and friends do not exist yet, so my gate opens too early and `hal.hh` fails to compile:

    src/hal/hal.hh:448:64: error: 'hal_query_value_u' has not been declared

Verified on a test branch: this PR + my #4251 commit cherry-picked on top.

**Comment by BsAtHome** [comment]
> It fails because of how I detect the query API in #4251. My by-name code (hal_getref_p etc.) only exists once the query API PR lands, so I gated it on
> #if defined(COMPONENT_TYPE_REALTIME)

That is a wrong assumption. You should not assume any of these defines being there. Your code trying to figure out whether the query code is present needs to be removed anyway.

FWIW, the component type defines are moved to hal.h because they are needed for the query API. This PR is prep work. The next PR will make sense of that again. By that time, your "hack" has become redundant. So, just wait it out for a moment. It is already hard enough not to break master. Trying to keep your not-presently-merged-and-needs-to-change-anyway code running at the same time makes life very difficult. ;-)

**Comment by grandixximo** [comment]
Fair, don't want to overcomplicate things, we'll hold on #4251
